### ISSUE TITLE
Expor API 

### ISSUE THREAD

**Issue by V1niciusTavares** [LukeVanHagen/Projeto3IF#5]
Como dev necessito de uma API para receber informações de registros

- [x] Criação de API em Laravel

**Comment by EmersonLima03** [comment]
Podemos empregar a ferramenta "Eloquent: API Resources" do Laravel. Essa ferramenta simplifica a conversão de modelos Eloquent em formato JSON, permitindo-nos personalizar como os dados desses modelos são exibidos quando acessados por meio de uma API.
